# Generated by Django 5.1.1 on 2024-10-08 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskModel',
            new_name='Task',
        ),
    ]
