# Generated by Django 5.1.1 on 2024-10-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_taskmodel_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_checked',
            new_name='checked',
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
