# Generated by Django 5.1.1 on 2024-10-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_task_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
