# Generated by Django 5.1.1 on 2024-10-09 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_alter_task_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='end_date',
            new_name='deadline',
        ),
    ]
