# Generated by Django 5.1.1 on 2024-10-09 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_rename_end_date_task_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='checked',
            new_name='done',
        ),
    ]
